name: CI_action

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: worksheet02/fe-vite

      - name: Run build
        run: npm run build
        working-directory: worksheet02/fe-vite

      - name: Run tests
        run: npm test
        working-directory: worksheet02/fe-vite